### PR TITLE
Little fix semicolons.

### PR DESCRIPTION
**Pull request by reus-github**

### CODE REVIEW

**Comment by urShadow** [comment]
What is the problem?

**Comment by reus-github** [comment]
A lot of errors "invalid function or declaration".

Example code:
`flags:gzapros(CMD_GANG);`
`alias:gzapros("gdodaj", "gzaproszenie", "ginvite", "gadd", "invite", "zapros");`

https://imgur.com/a/6mYxpJh

**Comment by urShadow** [comment]
Just delete these semicolons at the end.

flags:gzapros(CMD_GANG)**;**
alias:gzapros("gdodaj", "gzaproszenie", "ginvite", "gadd", "invite", "zapros")**;**

**Comment by urShadow** [comment]
Semicolons at the end of alias and flags declarations not allowed now.

**Pull request closed without merging**
